version: "3.1"
services:
  python:
    environment:
      - PYTHONBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bachelor_python_container
    ports:
      - 80:80
    volumes:
      - .:/app
    networks:
      - bottle_arangodb_network

  arangodb:
    image: arangodb:3.11.3
    container_name: bachelor_arango_container
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - ./arangodb:/var/lib/arangodb3
    networks:
      - bottle_arangodb_network

networks:
  bottle_arangodb_network:
